// Bakes the Simple Icons slug list into a module the client can consult synchronously.
//
// Only the *names* are baked in — roughly 31 KB of text, 14 KB over the wire. The path data
// stays on the server: `app/icons/[slug]/route.ts` reads it straight from the `simple-icons`
// package and serves one SVG per slug, so no logo geometry ever reaches the browser bundle.
//
// This is what lets `hasIcon()` answer "is there a real mark for this?" during render, for a
// skill name that was typed into the CMS minutes ago and that no build has ever seen.
import { writeFile, mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as simpleIcons from 'simple-icons'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const slugs = Object.values(simpleIcons)
  .map((icon) => icon.slug)
  .sort()

const out = `// GENERATED by scripts/gen-icons.mjs — do not edit.
//
// Simple Icons ${slugs.length} slugs (simpleicons.org, CC0-1.0). Names only; the path data is
// served by app/icons/[slug]/route.ts.
const PACKED =
  ${JSON.stringify(slugs.join(' '))}

export const ICON_SLUGS: ReadonlySet<string> = new Set(PACKED.split(' '))
`

await mkdir(join(root, 'src/generated'), { recursive: true })
await writeFile(join(root, 'src/generated/icon-slugs.ts'), out)
console.log(`gen-icons: ${slugs.length} slugs`)
