// Bakes the sources shown in the Code app into a module, so the window can display the
// real code without a bundler-specific `?raw` import.
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const FILES = [
  'src/os/store.tsx',
  'src/os/wm/Window.tsx',
  'src/os/shell/Dock.tsx',
  'src/os/search/Spotlight.tsx',
  'src/os/apps/Terminal.tsx',
  'src/data/projects.ts',
]

const entries = await Promise.all(
  FILES.map(async (path) => [path.replace(/^src\//, ''), await readFile(join(root, path), 'utf8')]),
)

const body = entries
  .map(([name, source]) => `  [${JSON.stringify(name)}, ${JSON.stringify(source)}],`)
  .join('\n')

const out = `// GENERATED by scripts/gen-sources.mjs — do not edit.
export const SOURCES: [string, string][] = [
${body}
]
`

await mkdir(join(root, 'src/generated'), { recursive: true })
await writeFile(join(root, 'src/generated/sources.ts'), out)
console.log(`gen-sources: ${entries.length} files`)
