// Writes migrations/0002_seed.sql from the real src/data modules, so the database starts out
// holding exactly what the site shipped with — no hand transcription, no drift.
//
// src/data is TypeScript with extensionless imports, which Node cannot load directly, so the
// module is bundled first with Vite (already a devDependency; nothing new is installed).

import { build } from 'vite'
import { writeFile, rm } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const tmp = join(root, 'node_modules', '.tmp-seed')

await build({
  root,
  logLevel: 'error',
  build: {
    ssr: join(root, 'src/data/content.ts'),
    outDir: tmp,
    emptyOutDir: true,
    rollupOptions: { output: { format: 'es', entryFileNames: 'content.mjs' } },
  },
})

const { FALLBACK } = await import(join(tmp, 'content.mjs'))

/** SQL literal. null and undefined become NULL; everything else is a quoted, escaped string. */
const q = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`)
const j = (v) => q(JSON.stringify(v))
const b = (v) => (v ? 1 : 0)

const rows = []

rows.push(`INSERT INTO site (id, name, initials, subtitle, paragraphs, email, resume_key) VALUES
  (1, ${q(FALLBACK.site.name)}, ${q(FALLBACK.site.initials)}, ${q(FALLBACK.site.subtitle)},
   ${j(FALLBACK.site.paragraphs)}, ${q(FALLBACK.site.email)}, NULL);`)

const os = FALLBACK.os
rows.push(`INSERT INTO os_content
  (id, term, neofetch_art, neofetch_rows, kb, ai_fallback, ai_suggestions, shortcuts) VALUES
  (1, ${j(os.term)}, ${q(os.neofetchArt)}, ${j(os.neofetchRows)}, ${j(os.kb)},
   ${q(os.aiFallback)}, ${j(os.aiSuggestions)}, ${j(os.shortcuts)});`)

FALLBACK.projects.forEach((p, i) => {
  rows.push(`INSERT INTO projects
  (id, slug, title, desktop_label, tagline, status_label, status_ok, stack, sections, links, aliases,
   note, caveat, cover_key, featured, published, display_order) VALUES
  (${q(p.id)}, ${q(p.slug)}, ${q(p.title)}, ${q(p.desktopLabel)}, ${q(p.tagline)}, ${q(p.status.label)}, ${b(p.status.ok)},
   ${j(p.stack)}, ${j(p.sections)}, ${j(p.links)}, ${j(p.aliases ?? [])},
   ${q(p.note)}, ${q(p.caveat)}, NULL, ${b(p.featured)}, 1, ${i});`)
})

const simple = (table, list) =>
  list.forEach((e, i) => {
    rows.push(`INSERT INTO ${table} (id, title, detail, hint, published, display_order) VALUES
  (${q(`${table}-${i + 1}`)}, ${q(e.title)}, ${q(e.detail)}, ${q(e.hint)}, 1, ${i});`)
  })

simple('experience', FALLBACK.experience)
simple('education', FALLBACK.education)

FALLBACK.skills.forEach((g, i) => {
  rows.push(`INSERT INTO skills (id, heading, items, published, display_order) VALUES
  (${q(`skills-${i + 1}`)}, ${q(g.heading)}, ${j(g.items)}, 1, ${i});`)
})

FALLBACK.socialLinks.forEach((l, i) => {
  rows.push(`INSERT INTO social_links (id, slug, label, handle, url, pill, published, display_order)
  VALUES (${q(`social-${l.slug}`)}, ${q(l.slug)}, ${q(l.label)}, ${q(l.handle)}, ${q(l.url)},
   ${b(l.pill)}, 1, ${i});`)
})

const sql = `-- Generated by scripts/seed-d1.mjs from src/data. Re-runnable: regenerate, do not edit.
-- Seeds the database with the content the portfolio shipped with.

${rows.join('\n\n')}
`

await writeFile(join(root, 'migrations/0002_seed.sql'), sql)
await rm(tmp, { recursive: true, force: true })
console.log(`seed-d1: ${rows.length} rows -> migrations/0002_seed.sql`)
